
services:
  - type: web
    name: taskscoreplanner
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
